name: "Sample"

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: "Step#01"
        run: |
          echo "Step#01 - develop"
        shell: bash